### ISSUE TITLE
Tables Preprocessing and Split

### ISSUE THREAD

**Issue by shulkx** [voxel51/fiftyone-docs-search#13]
Hi Jacob,
Thanks for sharing the valuable experience. I recently worked on a similar project - build chatbot with company knowledge base (mostly in HTML format).
In your sharing, you mentioned that you chose to convert doc into markdown finally. About this, I have few questions:
- How about the tables (in html format), they might have different complex format (merge rows, column). As far as I know, the markdown is weak to express such kind of table.
- While splitting doc, the table could be another annoying part. For large table, with fixed chunk size, it is possible that the table is split into parts. Did you handle this in your project as well?

**Comment by jacobmarks** [comment]
Hi @shulkx , 

Thanks for the note, and the insightful questions. You have hit on something indeed!

This documentation search experiment exclusively used the textual data (in markdown), which absolutely has limitations when working with tables and other complex data. Another example of content I had to strip out entirely was images/gifs!

If you're interested in more advanced retrieval approaches, for now here are some resources I hope may be helpful:
- [LangChain Multi-Vector Retriever for RAG on tables, text, and images](https://blog.langchain.dev/semi-structured-multi-modal-rag/)
- [LlamaIndex Multi-Modal on PDF’s with tables](https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_pdf_tables.html)

And stay tuned... exciting stuff coming in the not-too-distance future 😉
