### ISSUE TITLE
ModuleNotFoundError: No module named 'fiftyone.__public__'

### ISSUE THREAD

**Issue by YQisme** [voxel51/fiftyone-docs-search#8]
(51) yq7@DESKTOP-95SB342:~/fiftyone-docs-search$ fiftyone-docs-search query "how to load a dataset"
Traceback (most recent call last):
  File "/home/yq7/enter/envs/51/bin/fiftyone-docs-search", line 5, in <module>
    from fiftyone.docs_search.cli import main
  File "/home/yq7/fiftyone-docs-search/fiftyone/__init__.py", line 10, in <module>
    from fiftyone.__public__ import *
ModuleNotFoundError: No module named 'fiftyone.__public__'

**Comment by jacobmarks** [comment]
Hi YQisme,

Do you have the FiftyOne library installed locally? I.e. with git clone https://github.com/voxel51/fiftyone.git?

Would you mind providing more details about your environment and the lead-up to this trace?
